export const site = {
  origin: 'https://dust2cosmos.com',
  appStore: 'https://apps.apple.com/us/app/dust-to-cosmos-universe-scale/id6760629100',
  updated: '2026-09-08',
  release: { version: '3.0', status: 'upcoming', targetDate: '2026-09-22' },
  featuring: {
    title: 'Best New Apps and Updates',
    canadaTitle: 'Hot This Week',
    month: '2026-07',
    us: 'https://apps.apple.com/us/ipad/room/6741173165',
    canada: 'https://apps.apple.com/ca/iphone/apps',
  },
};

export const locales = {
  en: {
    title: 'Dust to Cosmos 3.0 — Space Exploration for iPhone & iPad',
    description: 'Discover Dust to Cosmos 3.0 for iPhone and iPad: cinematic Earth, solar system exploration, AR sky guides and new cosmic journeys. Preview the upcoming update.',
    brand: 'Dust to Cosmos', home: 'Home', skip: 'Skip to content', menu: 'Open navigation', closeMenu: 'Close navigation',
    nav: ['What’s new', 'Made for iPad', 'Explore', 'Questions'],
    store: 'View on the App Store', storeShort: 'Get the app', download: 'Download the current version',
    release: '3.0 · Coming soon',
    heroTitle: 'Dust to Cosmos 3.0',
    heroLead: 'A universe worth getting lost in.',
    heroText: 'From the clouds of Earth to the edge of the Solar System. Your 3D space exploration app for iPhone and iPad, reimagined.',
    discover: 'Discover 3.0', heroNote: 'Preview the upcoming update. Start exploring with the current app today.',
    heroAlt: 'Cinematic concept artwork of Earth, with the Pacific Ocean and a thin blue atmosphere against deep black space',
    concept: '3.0 concept artwork', scroll: 'Keep exploring',
    featuredIntro: 'Featured by App Store editors', featuredMonth: 'July 2026', featuredRegion: 'United States · iPhone & iPad', featuredCanada: 'Canada · iPhone & iPad',
    cinemaLabel: 'New in 3.0', cinemaTitle: 'Come closer to our home planet.',
    cinemaIntro: 'Sunlight over an ocean. Clouds casting shadows. A blue atmosphere fading into the dark. Meet a more cinematic Earth—and keep exploring beyond it.',
    cinemaDetails: [
      ['Cinematic worlds', 'Explore a photographic Earth, a reimagined Sun, and richer planets and moons in the app’s interactive 3D renderer.'],
      ['Clouds with a history', 'See recent cloud observations and their capture times. Revisit available recorded frames, then continue into the Solar System at the same epoch.'],
      ['Wonder, with context', 'Keep observations, reconstructions and modeled effects distinguishable. The Sun combines archival observations and visual models; it is not a live solar feed.'],
    ],
    cinemaLink: 'See what’s included in Pro',
    ipadLabel: 'iPhone & iPad', ipadTitle: 'Your own window into the cosmos.',
    ipadIntro: 'A pocket universe on iPhone. An expansive observatory on iPad. Rotate a planet, explore a system, and give every discovery room to breathe.',
    ipadAlt: 'Anticipated Dust to Cosmos 3.0 iPad interface: cinematic Earth with compact information and four bottom navigation destinations',
    iphoneAlt: 'Anticipated Dust to Cosmos 3.0 iPhone interface: Saturn and its rings with compact exploration controls',
    mockupNote: 'AI-generated 3.0 UI previews. The interface is in development; final screens may change.',
    devices: [
      ['A proper iPad experience', 'Landscape exploration gives planets, system navigation and requested detail panels their own space.'],
      ['Same curiosity, either device', 'Explore, Now, Journeys and Journal bring the planned 3.0 navigation together on both iPhone and iPad.'],
      ['Made to be touched', 'Turn worlds with a drag. Move closer with a pinch. Follow your curiosity through connected celestial systems.'],
    ],
    voyageLabel: 'The next chapter in 3.0', voyageTitle: 'Take the controls. Follow the wonder.',
    voyageIntro: 'Pilot the DTC–01 to ten destinations. Complete observation tasks, earn boosts and collect stamps from your own virtual expedition.',
    voyageAlt: 'Concept artwork of a small original DTC–01-style research craft approaching Saturn during a virtual flight',
    voyageNote: 'Virtual-flight concept artwork. Historical spacecraft journeys use separate, attributed trajectory data.',
    voyageFacts: [['10', 'flight destinations'], ['109', 'Earth epochs'], ['18', 'documentaries']],
    journeys: [
      ['Voyager, with perspective', 'Explore Voyager 1 and 2 using public trajectory data. Revisit Voyager 2’s 1989 Neptune encounter, with reconstructed viewpoints clearly identified.'],
      ['Earth through deep time', 'Travel through 540 million years of reconstructed geography across 109 epochs, with six chapters linking early Earth to the present.'],
      ['A cinema of the cosmos', 'Discover 18 rendered documentaries with original stereo scores, per-film resume and source details. Return from the story to direct observation.'],
    ],
    exploreLabel: 'Find your next discovery', exploreTitle: 'One universe. So many ways in.',
    tabsLabel: 'Ways to explore Dust to Cosmos',
    tabs: [
      { name: 'Explore', number: '01', title: 'Follow the connections.', text: 'Move through planets, moons, star systems, black holes and deep-sky objects. Select a world, focus on it, then keep its larger system in view.', items: [['Connected systems', 'Earth and Moon, the Solar System, Jupiter, Saturn and beyond.'], ['Science Dossiers · Pro in 3.0', '24 curated dossiers with measurements, uncertainty and compatible comparisons.'], ['Observation library · Pro in 3.0', 'Guided photographic observations that preserve original image credits.']] },
      { name: 'Now', number: '02', title: 'Start with the sky around you.', text: 'Make today’s curiosity a place to begin. Explore Living Earth, inspect available cloud observations, or use a guided AR view to find a target in the sky.', items: [['Living Earth', 'A connected Earth experience with source times kept visible.'], ['AR sky guidance · expanded in Pro', 'Target directions, surrounding stars, horizon and observing guides. Moon finding stays free.'], ['Voyager observatory · Pro in 3.0', 'Public trajectory coverage and data dates, never an invented live position.']] },
      { name: 'Journeys', number: '03', title: 'Experience the scale of it all.', text: 'Compare sizes. Travel with light. Put cosmic time into perspective. In 3.0, go deeper with virtual flight, Earth’s interior, deep time and documentaries.', items: [['Cosmic scale', 'Size comparison, Journey of Light and the Cosmic Calendar.'], ['Earth Interior · Pro in 3.0', 'Rotate a 3D cutaway and explore physical depths. Representative depths remain free.'], ['Expanded journeys · Pro in 3.0', 'Ten flight destinations, the Neptune encounter, 109 Earth epochs and 18 films.']] },
      { name: 'Journal', number: '04', title: 'Keep what made you stop.', text: 'Save a scene, add a thought, and keep the source beside it. Your observations become a personal collection you can return to.', items: [['Observation notebook · Pro', 'Saved scenes and viewpoints, notes, source records and comparison exports.'], ['Continue your expedition · Pro in 3.0', 'Flight stamps, saved progress and per-film resume.'], ['Basic sharing stays free', 'Keep ordinary image sharing, source access and scientific context.']] },
    ],
    proLabel: 'Dust to Cosmos Pro', proTitle: 'Go deeper, with one purchase.',
    proIntro: '3.0 brings the expanded experiences together in the same non-consumable Pro purchase. No new subscription. No separate ticket for each journey.',
    freeTitle: 'Curiosity comes first', freeText: 'Core exploration, existing facts and sources, scientific corrections, basic sharing and frame-rate choices remain free. Try Cinematic in the actual scene with a 10-second preview.',
    proList: ['Cinematic presentation & available cloud replay', 'Expanded AR guides & Earth Interior', 'Science Dossiers, observations & notebooks', 'Voyage, Voyager history & Earth Through Time', '18 documentaries & the Living Earth app icon'],
    proNote: '3.0 is in preparation. Availability and regional pricing will be shown in the app at release.',
    truthTitle: 'Beautiful. And honest about what you see.',
    truthText: 'Dust to Cosmos is a space exploration and astronomy education app by SnapWorks Lab for iPhone and iPad. It brings connected 3D worlds, cosmic scale and source-aware science together. Truth Class labels distinguish observations, reconstructions and inferred models, so a beautiful image never has to stand in for evidence.',
    sourceLabel: 'Explore the underlying science',
    sourceNote: 'Source organizations provide scientific data; they do not endorse this app. Cloud observations can be delayed or missing. Early Earth environments and internal materials include explanatory models.',
    faqTitle: 'A few things before you launch.',
    faq: [
      ['What is Dust to Cosmos?', 'Dust to Cosmos: Universe Scale is a 3D space exploration app for iPhone and iPad, made by SnapWorks Lab. Explore connected planets, moons, stars, black holes and deep-sky objects, compare their sizes, and discover cosmic time with visible scientific sources.'],
      ['Is Dust to Cosmos 3.0 available now?', '3.0 is an upcoming update, with a target of September 22, 2026. The date is a release goal, not a guaranteed launch. App Store links on this page open the currently published app. The generated 3.0 screen previews show a proposed interface that may change.'],
      ['Does it support iPad as well as iPhone?', 'Yes. Dust to Cosmos is a universal iPhone and iPad app. iPad exploration uses a landscape workspace with room for celestial systems and detail panels. The planned 3.0 navigation brings the same four destinations to both devices.'],
      ['What stays free, and what is included in Pro?', 'Core exploration, existing science facts, sources, corrections, basic sharing and frame-rate settings stay free. A single non-consumable Pro purchase covers the expanded experiences, including Cinematic presentation, cloud replay when records are available, expanded AR, Earth Interior, Science Dossiers, notebooks and the new 3.0 journeys. Regional prices are shown in the app.'],
      ['Is the imagery live, observed or simulated?', 'It depends on the feature. Cloud observations show capture times and can have gaps. The cinematic Sun uses archival data and modeled effects. Voyager uses public trajectory coverage, while piloted flight is virtual. Deep-time geography is reconstructed; early environments are modeled. Source and Truth Class information distinguish these cases.'],
      ['Can I use it offline?', 'Bundled celestial content and offline science materials can be explored without a continuous connection. Fresh cloud observations and other network data need internet access. Cloud replay depends on the validated records actually available on the device.'],
      ['Was Dust to Cosmos featured on the App Store?', 'Yes. In July 2026, Dust to Cosmos appeared in “Best New Apps and Updates” in the United States and “Hot This Week” in Canada, on both iPhone and iPad. These placements were documented on July 4, 2026; that is the verification date, not a confirmed first day of featuring. Apple’s collections change over time. This recognition of the app is separate from the upcoming 3.0 release.'],
    ],
    finalTitle: 'The universe is already in your hands.', finalText: 'Start exploring today. A whole new depth arrives with 3.0.',
    footerText: 'Made with curiosity by SnapWorks Lab.', privacy: 'Privacy', support: 'Support', sources: 'Science & sources',
    updated: 'Page updated September 8, 2026',
  },
  ko: {
    title: '우주먼지 3.0 — iPhone·iPad로 만나는 3D 우주 탐험',
    description: '우주먼지 3.0을 미리 만나보세요. iPhone과 iPad에서 시네마틱 지구, 태양계 탐험, AR 하늘 찾기, 직접 항해와 지구의 시간을 경험하는 우주 탐험 앱입니다.',
    brand: '우주먼지', home: '처음으로', skip: '본문으로 건너뛰기', menu: '메뉴 열기', closeMenu: '메뉴 닫기',
    nav: ['새로운 3.0', 'iPad에서', '탐험하기', '자주 묻는 질문'],
    store: 'App Store에서 보기', storeShort: '앱 다운로드', download: '현재 버전 다운로드',
    release: '3.0 · 출시 예정',
    heroTitle: '우주먼지 3.0', heroLead: '우주를 보는 새로운 깊이.',
    heroText: '지구의 구름에서 태양계 너머까지. iPhone과 iPad로 만나는, 더 깊고 아름다워진 3D 우주 탐험 앱.',
    discover: '3.0 미리 보기', heroNote: '새로운 업데이트를 미리 만나보세요. 지금은 현재 출시된 앱으로 탐험을 시작할 수 있어요.',
    heroAlt: '검은 우주를 배경으로 태평양과 얇은 푸른 대기가 드러나는 지구의 시네마틱 콘셉트 이미지',
    concept: '3.0 콘셉트 이미지', scroll: '아래로 탐험하기',
    featuredIntro: 'App Store 에디터가 소개한 앱', featuredMonth: '2026년 7월', featuredRegion: '미국 · iPhone·iPad', featuredCanada: '캐나다 · iPhone·iPad',
    cinemaLabel: '3.0의 새로운 모습', cinemaTitle: '우리가 사는 행성에 한 걸음 더 가까이.',
    cinemaIntro: '바다 위로 번지는 햇빛. 그림자를 드리우는 구름. 어둠 속으로 스며드는 푸른 대기. 새로워진 지구를 만나고, 그 너머로 탐험을 이어가세요.',
    cinemaDetails: [
      ['더 깊어진 시네마틱', '사진 같은 지구, 새롭게 표현한 태양, 더 풍부해진 행성과 위성을 직접 움직이는 3D 장면으로 만나요.'],
      ['시간을 담은 구름', '최근 구름 관측과 촬영 시각을 함께 확인해요. 확보된 기록을 다시 보고, 같은 시각의 태양계로 이어갈 수 있어요.'],
      ['아름다움에도 근거를', '관측과 재구성, 모델 효과를 구별해요. 태양은 보관 관측과 시각 모델을 조합한 표현이며, 현재 태양 활동의 생중계는 아니에요.'],
    ],
    cinemaLink: 'Pro에 담긴 경험 살펴보기',
    ipadLabel: 'iPhone과 iPad', ipadTitle: '손안의 우주, 더 넓은 관측실.',
    ipadIntro: 'iPhone에서는 언제 어디서나. iPad에서는 한층 넓고 여유롭게. 행성을 돌리고, 천체계를 오가며, 발견하는 순간에 푹 빠져보세요.',
    ipadAlt: '시네마틱 지구와 작은 상단 정보, 하단 네 메뉴를 담은 우주먼지 3.0 iPad 예상 UI',
    iphoneAlt: '토성과 고리, 간결한 탐험 도구를 담은 우주먼지 3.0 iPhone 예상 UI',
    mockupNote: 'AI로 제작한 3.0 예상 UI입니다. 현재 인터페이스를 개발 중이며 최종 화면은 달라질 수 있어요.',
    devices: [
      ['iPad를 위한 넓은 화면', '가로 화면에서 천체와 이동 메뉴를 여유롭게 보고, 필요할 때 상세 정보를 펼쳐요.'],
      ['어느 기기에서도 같은 흐름', '새로운 3.0 UI는 탐색·지금·여정·기록, 네 가지 목적을 iPhone과 iPad에 같은 순서로 모아요.'],
      ['손끝으로 이어지는 탐험', '드래그로 천체를 돌리고, 핀치로 가까이 다가가세요. 연결된 천체계를 따라 호기심도 자연스럽게 이어져요.'],
    ],
    voyageLabel: '3.0에서 넓어지는 여정', voyageTitle: '직접 조종해 만나는 다음 세계.',
    voyageIntro: 'DTC–01을 타고 열 곳의 목적지로 향하세요. 관측 과제를 수행하고, 부스트를 얻고, 나만의 가상 항해에 스탬프를 남겨요.',
    voyageAlt: '토성으로 향하는 DTC–01 스타일의 작은 탐사선을 표현한 가상 비행 콘셉트 이미지',
    voyageNote: '가상 비행 콘셉트 이미지입니다. 실제 탐사선의 역사 여정은 별도의 공개 궤적 자료를 사용해요.',
    voyageFacts: [['10', '곳의 비행 목적지'], ['109', '개의 지구 시대'], ['18', '편의 다큐멘터리']],
    journeys: [
      ['보이저가 지나온 길', '공개 궤적 자료로 보이저 1·2호를 살펴보세요. 재구성한 시점과 실제 궤적을 구별하며, 1989년 보이저 2호의 해왕성 조우로 돌아가요.'],
      ['5억 4천만 년의 지구', '109개 시대에 걸친 지리 재구성을 탐험하세요. 여섯 개의 장이 초기 지구부터 오늘의 지구까지 이어져요.'],
      ['우주를 만나는 시네마관', '3D 렌더로 펼쳐지는 18편의 다큐멘터리와 오리지널 스테레오 스코어. 작품마다 이어 보고, 출처를 읽고, 직접 관찰로 돌아와요.'],
    ],
    exploreLabel: '다음 발견을 찾아서', exploreTitle: '하나의 우주, 저마다의 탐험.', tabsLabel: '우주먼지를 탐험하는 방법',
    tabs: [
      { name: '탐색', number: '01', title: '연결된 세계를 따라가요.', text: '행성과 위성, 항성계와 블랙홀, 심우주까지. 천체를 고르고 가까이 관찰한 뒤, 더 큰 천체계로 탐험을 이어가세요.', items: [['연결된 천체계', '지구와 달, 태양계, 목성계와 토성계, 그리고 그 너머까지.'], ['과학 자료 · 3.0 Pro', '24개 자료의 측정값과 오차를 읽고, 비교할 수 있는 수치를 함께 살펴봐요.'], ['관측 자료실 · 3.0 Pro', '실제 관측 사진의 가이드를 따라가며 원본 이미지의 출처도 확인해요.']] },
      { name: '지금', number: '02', title: '오늘의 하늘에서 시작해요.', text: '살아 있는 지구를 만나고, 확보된 구름 관측을 살펴보고, AR 안내로 오늘 궁금한 하늘의 대상을 찾아보세요.', items: [['살아 있는 지구', '자료의 시각을 확인하며 지구와 같은 시각의 태양계를 연결해요.'], ['AR 하늘 찾기 · Pro 확장', '대상 방향과 주변 별, 지평선, 관측 가이드. 달 찾기는 계속 무료예요.'], ['탐사선 관측실 · 3.0 Pro', '공개 궤적의 유효 범위와 자료 날짜를 함께 표시해요. 실시간 위치로 꾸미지 않아요.']] },
      { name: '여정', number: '03', title: '우주의 크기와 시간을 느껴요.', text: '천체의 크기를 비교하고, 빛과 함께 이동하고, 우주의 시간을 체감해요. 3.0에서는 직접 비행, 지구 내부와 과거, 다큐멘터리까지 더 깊이 들어가요.', items: [['우주의 스케일', '크기 비교, 빛의 여정, 우주 달력으로 숫자를 경험으로 바꿔요.'], ['지구 내부 · 3.0 Pro', '3D 단면을 돌려 물리적인 깊이를 탐색해요. 대표 깊이는 무료로 만날 수 있어요.'], ['새로운 여정 · 3.0 Pro', '열 곳의 비행 목적지, 해왕성 조우, 109개 지구 시대, 18편의 다큐멘터리.']] },
      { name: '기록', number: '04', title: '오래 보고 싶은 순간을 남겨요.', text: '장면을 저장하고 생각을 적고, 그 옆에 출처도 간직하세요. 다시 돌아갈 수 있는 나만의 관측 기록이 쌓여요.', items: [['관측 노트 · Pro', '저장 장면과 시점, 메모, 출처 기록과 비교 내보내기.'], ['탐험 이어가기 · 3.0 Pro', '비행 스탬프와 진행 상황을 남기고, 다큐멘터리는 보던 곳부터 이어 봐요.'], ['기본 공유는 계속 무료', '일반 이미지 공유와 출처 확인, 과학적 맥락을 자유롭게 이용해요.']] },
    ],
    proLabel: '우주먼지 Pro', proTitle: '한 번의 구매로 더 깊은 우주.',
    proIntro: '3.0의 확장 경험을 기존의 단일 Pro에 함께 담아요. 새로운 구독이나 여정마다 따로 사는 이용권은 없어요.',
    freeTitle: '호기심에는 문턱 없이', freeText: '기본 탐험과 기존 과학 정보, 출처와 정정, 일반 공유와 FPS 선택은 계속 무료예요. 실제 장면에서 10초간 시네마틱도 미리 볼 수 있어요.',
    proList: ['시네마틱 연출과 확보된 구름 기록 재생', '확장 AR 가이드와 지구 내부 탐색', '과학 자료·관측 자료실·관측 노트', '직접 항해·보이저 역사·지구의 시간', '18편 다큐멘터리와 Living Earth 앱 아이콘'],
    proNote: '3.0은 출시 준비 중이에요. 출시 시 이용 가능한 기능과 지역별 가격은 앱에서 안내해요.',
    truthTitle: '아름답게 보여주고, 정직하게 설명해요.',
    truthText: '우주먼지(Dust to Cosmos: Universe Scale)는 SnapWorks Lab이 만드는 iPhone·iPad용 3D 우주 탐험·천문 교육 앱입니다. 연결된 천체와 우주의 스케일을 체험하고, 과학적 출처를 함께 확인할 수 있어요. Truth Class는 관측, 재구성, 추정 모델을 구별해 아름다운 이미지가 과학적 근거를 대신하지 않도록 해요.',
    sourceLabel: '바탕이 되는 과학 자료', sourceNote: '자료 제공 기관이 이 앱을 보증하거나 추천한다는 뜻은 아닙니다. 구름 관측은 지연되거나 누락될 수 있고, 초기 지구 환경과 내부 재질에는 설명용 모델이 포함됩니다.',
    faqTitle: '탐험을 시작하기 전에.',
    faq: [
      ['우주먼지는 어떤 앱인가요?', '우주먼지(Dust to Cosmos: Universe Scale)는 SnapWorks Lab의 iPhone·iPad용 3D 우주 탐험 앱입니다. 연결된 행성과 위성, 항성, 블랙홀과 심우주를 둘러보고, 천체의 크기와 우주의 시간을 과학적 출처와 함께 탐험할 수 있어요.'],
      ['3.0은 지금 사용할 수 있나요?', '3.0은 2026년 9월 22일을 목표로 준비 중인 업데이트입니다. 목표일은 확정된 출시를 보장하지 않아요. 이 페이지의 App Store 링크는 현재 출시된 앱으로 연결됩니다. 생성된 3.0 예상 화면은 개발 중인 UI로, 최종 화면은 달라질 수 있어요.'],
      ['iPhone뿐 아니라 iPad도 지원하나요?', '네. 우주먼지는 iPhone과 iPad를 함께 지원하는 유니버설 앱입니다. iPad에서는 가로 화면을 활용해 천체계와 상세 정보를 여유롭게 살펴볼 수 있어요. 새로운 3.0 UI는 두 기기에 같은 네 가지 목적 메뉴를 제공할 예정입니다.'],
      ['무료 기능과 Pro는 어떻게 다른가요?', '기본 탐험, 기존 과학 정보와 출처, 정정, 일반 공유, FPS 선택은 무료로 유지됩니다. 단일 비소모성 Pro 구매에 시네마틱, 확보된 구름 기록 재생, 확장 AR, 지구 내부, 과학 자료와 노트, 새로운 3.0 여정이 포함됩니다. 지역별 가격은 앱에서 안내해요.'],
      ['실시간 관측인가요, 시뮬레이션인가요?', '기능마다 달라요. 구름은 촬영 시각을 표시하는 관측 자료이며 누락될 수 있어요. 태양은 보관 자료와 모델 효과를 조합합니다. 보이저는 공개 궤적을 사용하고 직접 조종은 가상 비행이에요. 과거 지리는 재구성이며 초기 환경은 모델입니다. 출처와 Truth Class에서 이를 구별해요.'],
      ['인터넷 없이도 사용할 수 있나요?', '앱에 포함된 천체 콘텐츠와 오프라인 과학 자료는 계속 연결하지 않아도 볼 수 있어요. 최신 구름과 외부 자료를 새로 받으려면 인터넷이 필요합니다. 구름 재생은 기기에 실제로 확보된 검증 기록에 따라 달라져요.'],
      ['App Store에 선정된 적이 있나요?', '네. 2026년 7월 미국 App Store의 ‘Best New Apps and Updates’, 캐나다의 ‘Hot This Week’에 소개됐어요. 두 지역 모두 iPhone과 iPad 목록에서 2026년 7월 4일 확인한 기록이 있어요. 7월 4일은 확인일이며 최초 선정 시작일을 뜻하지 않습니다. Apple의 목록은 수시로 변경되며, 이 이력은 출시 예정인 3.0과 별개입니다.'],
    ],
    finalTitle: '이제, 당신의 우주를 만나세요.', finalText: '오늘 탐험을 시작하세요. 3.0이 새로운 깊이로 이어집니다.',
    footerText: 'SnapWorks Lab이 호기심으로 만듭니다.', privacy: '개인정보 처리', support: '고객 지원', sources: '과학과 출처',
    updated: '2026년 9월 8일 갱신',
  },
};
